services:
  front:
    build: ./frontend
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
  api:
    build: ./backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend/src:/app/src
    ports:
      - 5000:5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprodplease

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
