GET http://localhost:5000/api/skill
Content-Type: application/json

###

POST http://localhost:5000/api/skill
Content-Type: application/json

{
	"name" : "PHP"
}

###

PUT http://localhost:5000/api/skill
Content-Type: application/json

{
	"id" : 1,
	"newData": {
		"name": "Javascript"
	}
}

###

DELETE  http://localhost:5000/api/skill
Content-Type: application/json

{
	"id": 7
}